### ISSUE TITLE
Update for Firefox 36? (not funcional, stick on "Loading..." forever)

### ISSUE THREAD

**Issue by Dioxaz** [littlebtc/nicofox#37]
According to my quick web searches, it seems like the problem I'm currently having (videos don't download, they just never pass the "Loading..." step) are really caused by the migration to Firefox 36.

When rolling back to Firefox 35, the plugin works again.

I found no other feedback or reports of this problems other than obscure 2ch threads and a topic in a German forum. It seems like no other English-speaking person on the earth uses this plugin ( :rolleyes: ).

Hoping the "issues" page is not abandoned.

**Comment by jrdp18** [comment]
Just updated mine. Indeed, it just keeps loading in FF36.

**Comment by nomakewan** [comment]
As a Nightly user, I've seen this for a lot longer. It affects all plugins that request external filesystem access due to a patch made to an obscure bit of legacy code within Firefox. It has broken DownThemAll, Video Downloadhelper and Nicofox. VDH just updated today to fix the bug but so far it's not been fixed in anything else.

For exact details of the problem, please see: https://github.com/AndrewNeo/faextender/issues/32 and https://blog.mozilla.org/addons/2015/01/13/compatibility-for-firefox-36/

**Comment by littlebtc** [comment]
Thanks for finding the problems :angel: 
I am busy at other projects, but I still plan to fix it and release ASAP.

There are a lot more to fix in the future (e.g. E10S) so the total refactor will be needed later :(

**Comment by littlebtc** [comment]
我做了一個臨時的緊急修正版本，歡迎大家測試看看有沒有其他問題，沒有的話我會儘快送到 addons.mozilla.org 上

I made a quick hotfix prerelease, please test it and report any issues you encountered. If none, I will send the release to the AMO soon.

https://github.com/littlebtc/nicofox/releases/tag/1.0b6pre-hotfix

**Comment by Dioxaz** [comment]
Great. Thank you very much for your quick feedbacks. I confirm the plugin seems to work again with Firefox 36.0.1 with the fix. However, I only tested it on one video for now.
